---

# Configure systemd-timesyncd service
- name: Configure systemd-timesyncd
  include_tasks: timesyncd.yml
  tags:
    - timesyncd

# Configure timezone settings
- name: Configure timezone
  include_tasks: timezone.yml
  tags:
    - timezone

# Configure RTC
- name: Configure RTC
  include_tasks: rtc.yml
  tags:
    - rtc
