---
- name: Ensure util-linux is installed (provides hwclock)
  ansible.builtin.apt:
    name:
      - util-linux
    state: present
    update_cache: true
  when: time_set_rtc

- name: Check if `hwclock` is available
  ansible.builtin.command: which hwclock
  register: hwclock_check
  ignore_errors: true
  when: time_set_rtc
  changed_when: false

- name: Set fact if hwclock is available
  ansible.builtin.set_fact:
    has_hwclock: "{{ hwclock_check.rc == 0 }}"
  when: time_set_rtc

- name: Synchronize hardware clock from system time
  ansible.builtin.command: hwclock --systohc
  when: (has_hwclock | default(false)) and time_set_rtc
  changed_when: false

- name: Persist rtc module load across reboots
  ansible.builtin.copy:
    dest: /etc/modules-load.d/rtc.conf
    content: "rtc\n"
    owner: root
    group: root
    mode: '0644'
  when: time_set_rtc

- name: Show RTC date
  ansible.builtin.command: hwclock --show
  register: rtc_time
  when: time_set_rtc
  changed_when: false

- name: Print RTC date
  ansible.builtin.debug:
    msg: "RTC Time: {{ rtc_time.stdout }}"
  when: time_set_rtc
