---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  tasks:

    - name: Install Docker
      ansible.builtin.include_role:
        name: h33n0k.tools.docker
        tasks_from: install
