---
driver:
  name: docker

provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: ../../../../../../../../ansible.cfg

platforms:

  - name: debian11
    image: geerlingguy/docker-debian11-ansible:latest
    command: /lib/systemd/systemd
    environment:
      container: docker
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /run
      - /run/lock
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
    ansible_variables:
      ansible_python_interpreter: /usr/bin/python3.9

verifier:
  name: testinfra
  options:
    v: true
    s: true
