---
- name: Ensure Docker Volumes exist on host
  ansible.builtin.include_tasks: volume.yml
  tags:
    - volume
  vars:
    volume: '{{ item }}'
  loop: '{{ docker_run.volumes }}'
  loop_control:
    label: '{{ item.host }}'

- name: Build Docker volume list
  ansible.builtin.set_fact:
    volumes_specs: >-
      {{ volumes_specs | default([]) + [item.host + ':' + item.container + ':' + (item.access | default('rw'))] }}
  loop: '{{ docker_run.volumes }}'
  loop_control:
    label: '{{ item.host }}'
