---
- name: Ensure fail2ban is installed
  ansible.builtin.apt:
    name:
      - fail2ban
    state: present
    update_cache: true

- name: Deploy common filter
  ansible.builtin.template:
    src: fail2ban/filter.d/common.local
    dest: /etc/fail2ban/filter.d/common.local
    owner: root
    group: adm
    mode: '0644'

- name: Disable default debian jails
  ansible.builtin.file:
    path: /etc/fail2ban/jail.d/defaults-debian.conf
    state: absent

- name: Setup fail2ban jail
  ansible.builtin.template:
    src: fail2ban/jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: adm
    mode: '0644'

- name: Enable fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: started
    enabled: true
