---
- name: Generate Token
  ansible.builtin.include_tasks: '{{ role_path }}/tasks/token.yml'
  when: nginx_proxy_manager_api_token is not defined

- name: Fetch Certificates
  ansible.builtin.uri:
    url: 'http://localhost:81/api/nginx/certificates'
    method: GET
    headers:
      Content-Type: 'application/json'
      Authorization: 'Bearer {{ nginx_proxy_manager_api_token }}'
    return_content: true
    status_code: 200
  register: fetched_certificates

- name: Set Certificates
  ansible.builtin.set_fact:
    certificates: '{{ fetched_certificates.content }}'
