---
docker_container:
  name: http-server
  image: crccheck/hello-world
  restart: unless-stopped
  ports:
    - '80:8000'
  volumes:
    - host: '/var/opt/http'
      container: '/www'
      type: directory
      access: rw
  networks:
    - name: http
      driver: bridge
      ipam_config:
        - subnet: 192.168.100.0/24
