---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars_files:
    - ./defaults/main.yml
  tasks:

    - name: Setup Volumes
      ansible.builtin.include_role:
        name: h33n0k.tools.docker
        tasks_from: volume
      vars:
        volume: '{{ item }}'
      loop: '{{ docker_volumes }}'
      loop_control:
        label: '{{ item.host }}'
