---
- name: Configure NGINX PROXY MANAGER
  hosts: all
  become: true

  collections:
    - h33n0k.tools
    - h33n0k.services

  tasks:

    - name: Start Container
      ansible.builtin.include_role:
        name: h33n0k.services.nginx_proxy_manager
        tasks_from: setup

    - name: Update Default User
      block:
        - name: Generate Token
          ansible.builtin.include_role:
            name: h33n0k.services.nginx_proxy_manager
            tasks_from: token
          vars:
            nginx_proxy_manager_users:
              - email: admin@example.com
                password: changeme
      rescue:
        - name: Skip next task - token generation failed
          set_fact:
            token_generated: false
      always:
        - name: Set flag if token generation succeeded
          set_fact:
            token_generated: true
          when: ansible_failed_result is not defined

    - name: Update Default User
      ansible.builtin.include_role:
        name: h33n0k.services.nginx_proxy_manager
        tasks_from: user/update
      vars:
        user:
          id: 1
          name: '{{ item.name }}'
          nickname: '{{ item.nickname }}'
          email: '{{ item.email }}'
          roles: '{{ item.roles }}'
          password:
            current: changeme
            new: '{{ item.password }}'
      loop: '{{ nginx_proxy_manager_users[:1] }}' # First Defined User
      loop_control:
        label: '{{ item.name }}'
      when: token_generated
