---
- name: Basic setup
  hosts: all
  become: true
  collections:
    - h33n0k.basics
  roles:
    - h33n0k.basics.time
    - h33n0k.basics.logging
    - h33n0k.security.firewall
    - h33n0k.tools.docker
    - h33n0k.basics.auth
