---
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: 'Lint ansible codebase'
    runs-on: 'ubuntu-latest'
    steps:

      - name: Checkout repository
        uses: 'actions/checkout@v3'

      - name: 'Setup Python 3'
        uses: 'actions/setup-python@v4'
        with:
          python: '3.11'

      - name: 'Setup virtual environment'
        run: |
          make init

      - name: 'Source virtual environment'
        run: |
          source venv/bin/activate

      - name: 'Install dependencies'
        run: |
          make prepare

      - name: 'Run linting with ansible-lint'
        run: |
          make lint

  test:
    name: 'Test updated ansible roles'
    runs-on: 'ubuntu-latest'
    needs: [lint]
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Setup Python 3'
        uses: 'actions/setup-python@v4'
        with:
          python: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y rsync

      - name: 'Setup virtual environment'
        run: |
          make init

      - name: 'Source virtual environment'
        run: |
          source venv/bin/activate

      - name: 'Install dependencies'
        run: |
          make prepare

      - name: Test changes
        run: |
          BASE=origin/main
          CURRENT_SHA="${{ github.event.pull_request.head.sha || github.sha }}"
          make test CHANGED_SINCE="$CURRENT_SHA"
