---
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint:
    name: 'Lint ansible codebase'
    runs-on: 'ubuntu-latest'
    steps:

      - name: 'Checkout project'
        uses: 'actions/checkout@v3'

      - name: 'Setup Python 3'
        uses: 'actions/setup-python@v4'
        with:
          python: '3.11'

      - name: 'Setup virtual environment'
        run: |
          make init

      - name: 'Source virtual environment'
        run: |
          source venv/bin/activate

      - name: 'Install dependencies'
        run: |
          make prepare

      - name: 'Run linting with ansible-lint'
        run: |
          make lint
